#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CCustom)
#pragma config(Sensor, S3,     loHTSMUX,       sensorI2CCustom)
#pragma config(Sensor, S4,     hiHTSMUX,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     leftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     elevatorMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rampMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    wrist1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    wrist2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    gripper1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    gripper2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    rampLatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define rightLightSensor        msensor_S3_1
#define centerLightSensor       msensor_S3_2
#define leftLightSensor         msensor_S3_3
#define sonarSensor             msensor_S3_4

#define touchSensor             msensor_S4_1
#define leftIR                  msensor_S4_3
#define rightIR                 msensor_S4_4

#if 0
/// Copyright (c) Titan Robotics Club. All rights reserved.
///
/// <module name="Auto.c" />
///
/// <summary>
///     This module is a template file and should not be modified except for
///     the above motor and sensor definitions. Code common to both Autonmous
///     and TeleOp modes should live in CommonCode.h. Code specific to only
///     Autonmous mode should live in AutoCode.h.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "JoystickDriver.c"
#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"

#define _AUTO_ONLY

#include "CommonCode.h"
#include "AutoCode.h"

/**
 *  This function is called to initialize the robot. It does initializations
 *  common to both Autonomous and TeleOp modes as well as initializations
 *  specific only to Autonomous mode.
 */
void RobotInit()
{
    CommonInit();
    AutoInit();
}   //RobotInit

/**
 *  This function is called before Autonomous mode starts.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void StartMode(int pgmMode)
{
    AutoStart();
}   //StartMode

/**
 *  This function is called after Autonomous mode ends.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void StopMode(int pgmMode)
{
    AutoStop();
}   //StopMode

/**
 *  This function is called to perform high frequency tasks that are common to
 *  both Autonomous and TeleOp modes as well as specific only to Autonomous
 *  mode.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void HiFreqTasks(int pgmMode)
{
    CommonHiFreqTasks();
    AutoHiFreqTasks();
}   //HiFreqTasks

/**
 *  This function is called to perform input tasks that are common to both
 *  Autonomous and TeleOp modes as well as specific only to Autonomous
 *  mode.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void InputTasks(int pgmMode)
{
    CommonInputTasks();
    AutoInputTasks();
}   //InputTasks

/**
 *  This function is called to perform the main competition tasks.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 *  @param time Specifies the running time since the mode started.
 */
void MainTasks(int pgmMode, float time)
{
    AutoTasks(time);
}   //MainTasks

/**
 *  This function is called to perform output tasks that are common to both
 *  Autonomous and TeleOp modes as well as specific only to Autonomous
 *  mode.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void OutputTasks(int pgmMode)
{
    AutoOutputTasks();
    CommonOutputTasks();
}   //OutputTasks

#include "..\ftclib\FtcAuto.h"
