#pragma config(Sensor, S1,     lightSensor,    sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\RobotCDrivers\drivers\lego-light.h"

#define LS_LOW_THRESHOLD        150
#define LS_HIGH_THRESHOLD       270

task main()
{
    LSsetInactive(lightSensor);
    while (true)
    {
        int lightValue = LSvalRaw(lightSensor);
        nxtDisplayTextLine(0, "LS=%d", lightValue);

        if (lightValue <= LS_LOW_THRESHOLD)
        {
            // Detected heavy ring.
            nxtDisplayCenteredBigTextLine(3, "HEAVY");
        }
        else if (lightValue <= LS_HIGH_THRESHOLD)
        {
            // Detected light ring.
            nxtDisplayCenteredBigTextLine(3, "LIGHT");
        }
        else
        {
            // Detected no ring.
            nxtDisplayCenteredBigTextLine(3, "NONE");
        }

        wait1Msec(50);
    }
}
