#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    gripper,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
    int pos = 0;
    bool btn2Pressed = false;
    bool btn3Pressed = false;
    servo[gripper] = 0;
    while (true)
    {
        getJoystickSettings(joystick);
        if (!btn2Pressed && joy1Btn(2))
        {
            btn2Pressed = true;
            pos += 10;
            if (pos > 255)
            {
                pos = 255;
            }
        }
        else if (btn2Pressed && !joy1Btn(2))
        {
            btn2Pressed = false;
        }

        if (!btn3Pressed && joy1Btn(3))
        {
            btn3Pressed = true;
            pos -= 10;
            if (pos < 0)
            {
                pos = 0;
            }
        }
        else if (btn3Pressed && !joy1Btn(3))
        {
            btn3Pressed = false;
        }
        nxtDisplayTextLine(0, "pos=%d", pos);
        servo[gripper] = pos;
        wait1Msec(50);
    }
}
