#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     topLimitSW,     sensorI2CCustom)
#pragma config(Sensor, S3,     botLimitSW,     sensorI2CCustom)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     conveyorMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     elevatorMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     marMotorRight, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     marMotorLeft,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftWrist,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    flap,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    rightWrist,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
    Correct behavior:
    Code should compile without errors or warnings.
*/

task main()
{
    while (true)
    {
        servo[servo7] = 100;
        servo[servo8] = 80;
        servo[servo6] = 80;
        wait1Msec(100);
    }
}
